name: First Workflow
on: workflow_dispatch
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello, World!"
      - name: Print date and sleep
        run: |
        date 
        sleep 5
        date
      - name: Print goodbye
        run: echo "Done - bye!"
